version: '3.7'

services:

  api:
    container_name: api
    build: ./api
    ports:
      - '5051:5051'

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'